on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/53fc9bee2431bc255b22e6459d952e14
          gist_title: Pr치ctica 2 - Push Button MPLAB X PIC assembler MPASM PIC18F4550
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F4550/Push_Button.X/push_button.asm
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/8bb114bfd15a3efda79eaa3736937d39
          gist_title: Pr치ctica 2 - Push Button MPLAB X PIC assembler MPASM PIC18F45K50
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F45K50/Push_Button.X/push_button.asm
          file_encoding: ISO-8859-1